### ISSUE TITLE
Prioritise native modules

### ISSUE THREAD

**Issue by mariotoffia** [dop251/goja_nodejs#42]
Hi and thanks for this wonderful project!! :)

I've been using it in our framework for a while and I saw that you downprioritized the resolving of native modules. Is it possible to do this configurable? 

I've done a ugly [hack](https://github.com/dop251/goja_nodejs/commit/ea69219be8f35e633d8a8e9c6bec67ede5110fda) to achieve this.

Cheers,
 Mario :)
 
 
![image](https://user-images.githubusercontent.com/1716527/206635621-beaf0837-2ec8-4140-bcc7-c2e3ce23d922.png)

**Comment by dop251** [comment]
Hi. 
I don't believe this is necessary, if you don't want a module override a native one, you could provide your own `SourceLoader` in which you would ignore a module if its name matches a native. It even gives you more flexibility because you can choose which ones you want overwritten and which ones you don't.

**Comment by mariotoffia** [comment]
Many thanks!! :)
